parameter_defaults:
  DeployedNetworkEnvironment:
    net_attributes_map:
      external:
        network:
          dns_domain: external.example.com.
          mtu: 1500
          name: external
          tags:
          - tripleo_network_name=External
          - tripleo_net_idx=2
          - tripleo_vip=true
        subnets:
          external_subnet:
            cidr: 10.0.0.0/24
            dns_nameservers: []
            gateway_ip: 10.0.0.1
            host_routes: []
            ip_version: 4
            name: external_subnet
            tags:
            - tripleo_vlan_id=10
      internal_api:
        network:
          dns_domain: internalapi.example.com.
          mtu: 1500
          name: internal_api
          tags:
          - tripleo_network_name=InternalApi
          - tripleo_net_idx=0
          - tripleo_vip=true
        subnets:
          internal_api_subnet:
            cidr: 172.16.1.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: internal_api_subnet
            tags:
            - tripleo_vlan_id=20
      tenant:
        network:
          dns_domain: tenant.example.com.
          mtu: 1500
          name: tenant
          tags:
          - tripleo_network_name=Tenant
          - tripleo_net_idx=1
        subnets:
          tenant_subnet:
            cidr: 172.16.0.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: tenant_subnet
            tags:
            - tripleo_vlan_id=50
    net_cidr_map:
      external:
      - 10.0.0.0/24
      internal_api:
      - 172.16.1.0/24
      tenant:
      - 172.16.0.0/24
    net_ip_version_map:
      external: 4
      internal_api: 4
      tenant: 4
resource_registry:
  OS::TripleO::Network: /usr/share/openstack-tripleo-heat-templates/network/deployed_networks.yaml
