parameter_defaults:
  ControlPlaneVipData:
    fixed_ips:
    - ip_address: 192.168.24.15
    name: control_virtual_ip
    network:
      tags:
      - 192.168.24.0/24
    subnets:
    - ip_version: 4
  VipPortMap:
    external:
      ip_address: 10.0.0.10
      ip_address_uri: 10.0.0.10
      ip_subnet: 10.0.0.10/24
    internal_api:
      ip_address: 172.16.1.85
      ip_address_uri: 172.16.1.85
      ip_subnet: 172.16.1.85/24
resource_registry:
  OS::TripleO::Network::Ports::ControlPlaneVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_ctlplane.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_external.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_internal_api.yaml
